### ISSUE TITLE
Tengo un error en el manifest

### ISSUE THREAD

**Issue by PWAobregon** [Jeluchu/waStickersOnline#1]
hola tengo un problema con esta parte del manifest

        val contentProviderAuthority = "$applicationId.provider.StickerContentProvider"
        manifestPlaceholders = mapOf("contentProviderAuthority" to contentProviderAuthority)
        buildConfigField("String", "CONTENT_PROVIDER_AUTHORITY", "\"${contentProviderAuthority}\"")

Al querer compilarla me marca este error: val cannot be reassigned, conozco poco de kotlin y no pude solucionarlo, no se si me podrias orientar como resolverlo

**Comment by jeluchu** [comment]
@PWAobregon perdona acabo de ver la issue que has creado, revisaré el posible problema a ver que puede estar pasando para poderlo corregir

**Comment by jeluchu** [comment]
Lo he revisado, era por una actualización que tuvo el Gradle hace unos meses, ya lo he actualizado junto a algunas librerías y también la actualización de Kotlin a la versión 1.5.0 puedes ver los cambios en el commit: 9301587029b6e493f44196c3d296aa95c6c889c8
