### ISSUE TITLE
Animated stickers & and sticker preview

### ISSUE THREAD

**Issue by LinkStatu** [Jeluchu/waStickersOnline#2]
Hi there,
I checked the app and it's great!
Can you make it support **animated stickers**? it will be great.
Also, I suggest adding **sticker preview** when someone click on the sticker to preview it.
Thanks.

**Comment by jeluchu** [comment]
Hello @LinkStatu!

Sorry for the delay in replying, I hadn't missed any notice of the issue, I'm glad you like it, I haven't updated the repository for a while, maybe I should also take a look to see if there is a possibility to migrate it to Jetpack Compose, or make another alternate repository with the example in Compose, anyway the first thing I will try to do will be to update everything that has been deprecated.

On the subject of animated stickers I would have to see it, I know that WhatsApp once released availability on that, but I did not get to look at what adaptations would have to do, I will investigate, anyway if you discover a way, you can always write me or make a pull request. And the preview could be cool, as well as the possibility of saving in favourites locally with Room Database.

**Comment by LinkStatu** [comment]
OK bro, I will be waiting. And sorry, I'm still a newbie at this, so unfortunately, I can't make a pull request, yet.

**Comment by jeluchu** [comment]
No problem, so far in these last two commits (c8b7a1c60364eaea40a3231532f475d73c03f8fc / b5d1a607754793272e836c050449e3d5ed019d09) I have updated a bit the code and the project dependencies that were quite outdated, and I have migrated many things to [my component library](https://github.com/jeluchu/jchucomponents).

**Comment by LinkStatu** [comment]
I tested the updates you made, there is an issue. When I uploaded my version to Play Store the stickers didn't appear for some reason. When I tested it on Android Studio, it works very well, but Idk why when I upload the Play Store copy (or rather a signed apk), the stickers don't appear. Here is a signed apk if you want to confirm: [link](https://drive.google.com/file/d/1P9jyxVz3fiNhgg4SyKRSIr8f5LO-yxTt/view?usp=sharing)

**Comment by jeluchu** [comment]
@LinkStatu I just tested the application and it crashes (I guess because there is no information), this is also useful to include a warning when there is no information.

On the other hand, do you have ProGuard rules activated? If so, you should indicate in the rules file the network models as follows:

`-keep class com.jeluchu.wastickersonline.features.sticker.models.** { *; }`

This way, when the application is signed and the code is obfuscated, that class will be excluded and will leave the passage to the network, so if that is the problem in your case, it should be solved in that way.

The proguard rules are written in the file "proguard-rules.pro", you can check in "build.gradle.kts" that this is added:

```
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
```

If you are, you should include the rule in Proguard as I said at the beginning of the commentary

**Comment by LinkStatu** [comment]
@jeluchu
Great! it worked as you said.
What about animated stickers adding possibility, did you check the compatibility with WhatsApp?
If there is no way to implement them in the app, I'll continue using it, np.

**Comment by jeluchu** [comment]
Great @LinkStatu! Maybe I should include a README indicating such things so there are no surprises like that. On the other hand, I haven't checked it yet, I'm quite active with the development of the other apps I have published and with the library of components that I told you about, at the moment I've updated the project, I need to check how WhatsApp is sending this kind of elements, I'll try to investigate it

**Comment by LinkStatu** [comment]
Ok, thank you and good luck!

**Comment by jeluchu** [comment]
@LinkStatu I inform you that in the last commit I uploaded (613a1ab0bbec0168ab6f47d755bde7a49f659e2a) I have already included support for animated stickers (currently without preview, but if it works, just check the last sticker pack added and add it to WhatsApp with the button), you will see that they are added and animated.

I have to see to include animated anime stickers, and not the default ones from WhatsApp.

**Comment by jeluchu** [comment]
@LinkStatu  Good news, I include also the preview for static and animated stickers in the last commit (1236286515057fdf09d91acfa2334e4add8080c2) so when you click on the stickers in the details screen, the view will be enlarged and the sticker will be shown bigger, and in the animated stickers, the animation of the sticker will be played.

This concludes this issue and I will close it, in case of new suggestions do not hesitate to indicate them by creating a new one. Thank you very much for your contribution to improve this app! 😄

**Comment by LinkStatu** [comment]
I just want to thank you for your efforts, now the app is great!!
One more thing, I have a question but can't ask it here, so I sent a message to you on twitter, please check it.
